services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ENVIRONMENT=dev
    restart: always
    volumes:
      - .:/code
      - /code/.venv
      - /code/postgres-data
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.docker
    command:
      ["uv", "run", "python", "-m", "app"]

  db:
    image: postgres:14
    restart: always
    env_file: .env.docker
    volumes:
      - ./postgres-data:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 15

volumes:
  data: {}