"""add map favoriting

Revision ID: 2c2a15b67078
Revises: 2715288484b9
Create Date: 2024-12-08 23:19:38.427212

"""
from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision = '2c2a15b67078'
down_revision = '2715288484b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_favorites',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('map_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], name=op.f('fk_map_favorites_map_id_maps'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_map_favorites_user_id_users'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_favorites'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_favorites')
    # ### end Alembic commands ###
