"""add mimetype to thumb/avatar

Revision ID: 2715288484b9
Revises: bc7f1bd3144b
Create Date: 2024-12-05 19:31:49.117256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2715288484b9'
down_revision = 'bc7f1bd3144b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thumbnails', sa.Column('mimetype', sa.String(), nullable=False))
    op.add_column('user_avatars', sa.Column('mimetype', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_avatars', 'mimetype')
    op.drop_column('thumbnails', 'mimetype')
    # ### end Alembic commands ###
