"""add last_played_at col to map

Revision ID: 2db4e44c1daa
Revises: 2aa1423c6c20
Create Date: 2024-12-05 05:34:23.536717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db4e44c1daa'
down_revision = '2aa1423c6c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('last_played_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'last_played_at')
    # ### end Alembic commands ###
