"""add thumbnail table

Revision ID: 2aa1423c6c20
Revises: 436a7fcada3a
Create Date: 2024-12-05 00:30:58.790183

"""
from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision = '2aa1423c6c20'
down_revision = '436a7fcada3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnails',
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('map_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], name=op.f('fk_thumbnails_map_id_maps'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thumbnails'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thumbnails')
    # ### end Alembic commands ###
